### ISSUE TITLE
JSON parse error with Azure SWA deployment

### ISSUE THREAD

**Issue by quinnhornblow** [geoffrich/svelte-adapter-azure-swa#78] opened 2022-10-10 03:51 UTC
Hey,

I've been migrating to the new version of Sveltekit (new routing layout etc). And I'm having trouble with API routes/endpoints when deploying to an azure static site.

As reference I have this basic app repo [here](https://github.com/quinnhornblow/sk-test), to test a variety of function calls. Theses are based on the Sveltekit docs:
- add function via API route
- random-number function via API route
- random-number via +page.server.js load function

Behavior observed:
- local development, all functions work as expected
- deployment to digitalocean with node adapter, all functions work as expected
- deployment to azure swa with svelte-adapter-azure-swa,
    - add function via API route (works)
    - random-number via +page.server.js load function (works)
    - random-number function via API route (fails)

The failed function returns the following error: *JSON.parse: unexpected end of data at line 1 column 1 of the JSON data*.

I'm struggling to understand why I get this error. Is it a bug in the adapter, something with the azure infrastructure, or do I need a better way to parse the json result?

Would appreciate any ideas or work-arounds.
Thanks

**Comment by FlippingBinary** [comment] 2022-10-11 14:32
I see two places you might be talking about.

`/random-n`: https://github.com/quinnhornblow/sk-test/blob/3229c913e91ecd3a388ac6274991a85d442802dd/app/src/routes/random-n/%2Bpage.svelte#L6

`/random-number`: https://github.com/quinnhornblow/sk-test/blob/3229c913e91ecd3a388ac6274991a85d442802dd/app/src/routes/random-number/%2Bpage.svelte#L12

Which part of your code results in the error? Do they both fail?

**Comment by quinnhornblow** [comment] 2022-10-19 01:50
Both routes fail to fetch from the `/api/random-number` endpoint. A successful random number is generated on the `/random-n` route using the `+page.server,js` load function.

**Comment by geoffrich** [comment] 2022-10-23 23:23
I was able to repro this in #88. The root issue here is having a route in `/api` - Azure SWA [reserves that route](https://learn.microsoft.com/en-us/azure/static-web-apps/apis-functions?source=recommendations#configuration) for API endpoints via individual Azure functions. Since there is no `random-number` Azure function, it returns a 404. If you move your endpoint to a separate route that does not start with API (e.g. `/random`) it works as expected.

It doesn't appear like you can override that behavior and expose your own routes inside `/api`:

> While the /api route is fixed, you have control over the source code folder location of the managed functions app.

Closing since this isn't a bug and there's not much an adapter can do. Opened #89 to document/warn when we detect this case.

**Closed by geoffrich** 2022-10-23 23:23 UTC

**Comment by goenitz96** [comment] 2023-03-21 16:37
Man I'm having the same issue, and sadly I cannot find a solution

**Comment by geoffrich** [comment] 2023-03-21 17:07
@goenitz96 mind opening a new issue with a reproduction?
