### ISSUE TITLE
On refresh, either the handle function doesn't recognize the cookie or the handle function doesn't run at all.

### ISSUE THREAD

**Issue by saym97** [geoffrich/svelte-adapter-azure-swa#80] opened 2021-12-23 14:04 UTC
How to reproduce the issue:
    Go to Todos route and add some tasks. Then refresh the page. All of the previous task should be gone and new user_id is assigned in the cookie, which means the request header when refreshing lost the user_id cookie.

**Comment by geoffrich** [comment] 2022-10-10 23:34
Not sure if this is still an issue or not. Transferring to this repo since I'm archiving the old demo repo post #77.

**Comment by geoffrich** [comment] 2022-10-18 23:44
I can no longer reproduce this. The deployed demo persists cookies in Firefox with the latest adapter and SvelteKit versions.

**Closed by geoffrich** 2022-10-18 23:44 UTC
